### ISSUE TITLE
求文章配套的源码文件

### ISSUE THREAD

**Issue by xbinglzh** [HuFY-dev/GEMS-GCN#1]
GraphSage与DGL实现同构图 Link 预测
 异构图 Link 预测 理论与DGL 源码实战

**Comment by HuFY-dev** [comment]
没有文章，代码参考https://github.com/snap-stanford/ogb/tree/master/examples/linkproppred/collab

**Comment by HuFY-dev** [comment]
没有文章，代码参考https://github.com/snap-stanford/ogb/tree/master/examples/linkproppred/collab
